apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osint-backend-data
  namespace: osint
  labels:
    app: osint-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osint-worker-data
  namespace: osint
  labels:
    app: osint-worker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
